In [29]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [30]:
%reload_kedro

[02/01/26 09:47:36] INFO     Resolved project path as: /Users/me/ysz-vc/label-train-serve/mykedro.  ]8;id=822148;file:///Users/me/ysz-vc/label-train-serve/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=596250;file:///Users/me/ysz-vc/label-train-serve/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#181\181]8;;\
                             To set a different path, run '%reload_kedro <project_root>'

[02/01/26 09:47:37] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=860683;file:///Users/me/ysz-vc/label-train-serve/.venv/lib/python3.12/site-packages/kedro_telemetry/plugin.py\plugin.py]8;;\:]8;id=961973;file:///Users/me/ysz-vc/label-train-serve/.venv/lib/python3.12/site-packages/kedro_telemetry/plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

                    INFO     Kedro project mykedro                                                  ]8;id=615656;file:///Users/me/ysz-vc/label-train-serve/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=767229;file:///Users/me/ysz-vc/label-train-serve/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=234255;file:///Users/me/ysz-vc/label-train-serve/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=910287;file:///Users/me/ysz-vc/label-train-serve/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#148\148]8;;\
                             'pipelines'

In [40]:
all_data_jsonl = catalog.load("all_data_jsonl")

all_data_jsonl

[02/01/26 09:53:48] INFO     Loading data from all_data_jsonl (SrslyDataset)...                ]8;id=447071;file:///Users/me/ysz-vc/label-train-serve/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=432753;file:///Users/me/ysz-vc/label-train-serve/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

<generator object read_jsonl at 0x1195d1940>

In [41]:
import pandas as pd

df = pd.DataFrame.from_records(all_data_jsonl)

df

,text,meta
0,Uber’s Lesson: Silicon Valley’s Start-Up Machi...,{'source': 'The New York Times'}
1,"Pearl Automation, Founded by Apple Veterans, S...",{'source': 'The New York Times'}
2,How Silicon Valley Pushed Coding Into American...,{'source': 'The New York Times'}
3,Women in Tech Speak Frankly on Culture of Hara...,{'source': 'The New York Times'}
4,Silicon Valley Investors Flexed Their Muscles ...,{'source': 'The New York Times'}
...,...,...
195,One on One: Jaron Lanier,{'source': 'The New York Times'}
196,"6 Months, $90,000 and (Maybe) a Great Idea",{'source': 'The New York Times'}
197,Microsoft’s Failed Yahoo Bid Risks Online Growth,{'source': 'The New York Times'}
198,Why Old Technologies Are Still Kicking,{'source': 'The New York Times'}
199,Trying to Add a Pulse to a World of Machines,{'source': 'The New York Times'}

In [ ]:
df = df.reset_index().rename(columns={"index": "id"})

df

,id,text,meta
0,0,Uber’s Lesson: Silicon Valley’s Start-Up Machi...,{'source': 'The New York Times'}
1,1,"Pearl Automation, Founded by Apple Veterans, S...",{'source': 'The New York Times'}
2,2,How Silicon Valley Pushed Coding Into American...,{'source': 'The New York Times'}
3,3,Women in Tech Speak Frankly on Culture of Hara...,{'source': 'The New York Times'}
4,4,Silicon Valley Investors Flexed Their Muscles ...,{'source': 'The New York Times'}
...,...,...,...
195,195,One on One: Jaron Lanier,{'source': 'The New York Times'}
196,196,"6 Months, $90,000 and (Maybe) a Great Idea",{'source': 'The New York Times'}
197,197,Microsoft’s Failed Yahoo Bid Risks Online Growth,{'source': 'The New York Times'}
198,198,Why Old Technologies Are Still Kicking,{'source': 'The New York Times'}
199,199,Trying to Add a Pulse to a World of Machines,{'source': 'The New York Times'}

In [38]:
# for index, r in df.iterrows():
#     df.loc[index, "meta"]["id"] = index

# df

In [ ]:
df["source"] = df["meta"].apply(lambda m: m["source"])

,id,text,meta,source
0,0,Uber’s Lesson: Silicon Valley’s Start-Up Machi...,{'source': 'The New York Times'},The New York Times
1,1,"Pearl Automation, Founded by Apple Veterans, S...",{'source': 'The New York Times'},The New York Times
2,2,How Silicon Valley Pushed Coding Into American...,{'source': 'The New York Times'},The New York Times
3,3,Women in Tech Speak Frankly on Culture of Hara...,{'source': 'The New York Times'},The New York Times
4,4,Silicon Valley Investors Flexed Their Muscles ...,{'source': 'The New York Times'},The New York Times
...,...,...,...,...
195,195,One on One: Jaron Lanier,{'source': 'The New York Times'},The New York Times
196,196,"6 Months, $90,000 and (Maybe) a Great Idea",{'source': 'The New York Times'},The New York Times
197,197,Microsoft’s Failed Yahoo Bid Risks Online Growth,{'source': 'The New York Times'},The New York Times
198,198,Why Old Technologies Are Still Kicking,{'source': 'The New York Times'},The New York Times
199,199,Trying to Add a Pulse to a World of Machines,{'source': 'The New York Times'},The New York Times

In [ ]:
df[["id", "text", "source"]]

,id,text,source
0,0,Uber’s Lesson: Silicon Valley’s Start-Up Machi...,The New York Times
1,1,"Pearl Automation, Founded by Apple Veterans, S...",The New York Times
2,2,How Silicon Valley Pushed Coding Into American...,The New York Times
3,3,Women in Tech Speak Frankly on Culture of Hara...,The New York Times
4,4,Silicon Valley Investors Flexed Their Muscles ...,The New York Times
...,...,...,...
195,195,One on One: Jaron Lanier,The New York Times
196,196,"6 Months, $90,000 and (Maybe) a Great Idea",The New York Times
197,197,Microsoft’s Failed Yahoo Bid Risks Online Growth,The New York Times
198,198,Why Old Technologies Are Still Kicking,The New York Times
199,199,Trying to Add a Pulse to a World of Machines,The New York Times